#! /bin/sh
# Clone/update ubuntu-bugpatterns and publish bugpatterns.xml
set -e

gitdir="$HOME/ubuntu-bugpatterns"
datafile="$gitdir/bugpatterns.xml"
# Allow to specify the destination externally
destination=${DESTINATION:-"$HOME/public_html/bugpatterns/bugpatterns.xml"}

destdir=$(dirname "$destination")
mkdir -p "$destdir"

if [ -d "$gitdir" ]; then
    echo "Status: In-place update from git"
    git -C "$gitdir" pull -q
else
    echo "Status: Initial clone"
    git clone --depth=1 https://git.launchpad.net/~ubuntu-bugcontrol/apport/+git/ubuntu-bugpatterns "$gitdir"
fi

# Atomic update (only the file is in the web path)
cp -a "$datafile" "${destination}.new"
echo "Status: atomic exchange"
mv "${destination}.new" "${destination}"
